platform :ios, '10.3'

use_frameworks!

target 'Presentables_Example' do
    pod 'Presentables', :path => '../'
    pod 'SnapKit'
    
    target 'Presentables_Tests' do
        inherit! :search_paths
        
        pod 'Quick'
        pod 'Nimble'
    end
end
