platform :ios, '10.3'

inhibit_all_warnings!

use_frameworks!

target 'Presentables_Example' do
    pod 'Presentables', :path => '../'
    pod 'SnapKit'
    
    target 'Presentables_Tests' do
        inherit! :search_paths
        
        pod 'Quick'
        pod 'Nimble'
        #pod 'FBSnapshotTestCase'
        #pod 'Nimble-Snapshots'
    end
end
