platform :ios, '10.1'

inhibit_all_warnings!

use_frameworks!

target 'Presentables_Example' do
    pod 'Presentables', :path => '../'
    pod 'SnapKit', '~> 3.2.0'
    
    target 'Presentables_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
